// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.
import { FirebaseOptions } from 'firebase/app';

// Your web app's Firebase configuration will be populated here automatically
export const firebaseConfig: FirebaseOptions = {
  apiKey: "...",
  authDomain: "...",
  projectId: "...",
  storageBucket: "...",
  messagingSenderId: "...",
  appId: "..."
};
